import type {
  Campaign,
  ContentPackage,
  ChannelVariant,
  ReviewRecord,
  PublishJob,
  MetricDaily,
} from "@/types/content_package";

export const sampleCampaigns: Campaign[] = [
  {
    id: "camp_001",
    name: "春季アカデミー募集キャンペーン",
    objective: "acquisition",
    start_date: "2026-03-01",
    end_date: "2026-04-30",
    status: "active",
    content_ids: ["cnt_001", "cnt_002"],
  },
  {
    id: "camp_002",
    name: "プロテインサブスク継続施策",
    objective: "retention",
    start_date: "2026-02-01",
    end_date: "2026-03-31",
    status: "active",
    content_ids: ["cnt_003"],
  },
  {
    id: "camp_003",
    name: "管理栄養士監修シリーズ",
    objective: "trust",
    start_date: "2026-02-10",
    end_date: "2026-05-31",
    status: "active",
    content_ids: ["cnt_004", "cnt_005"],
  },
  {
    id: "camp_004",
    name: "管理栄養士インターン募集",
    objective: "recruitment",
    start_date: "2026-03-15",
    end_date: "2026-04-15",
    status: "planning",
    content_ids: ["cnt_006"],
  },
  {
    id: "camp_005",
    name: "スポーツ栄養セミナー 4月開催",
    objective: "event",
    start_date: "2026-03-20",
    end_date: "2026-04-20",
    status: "active",
    content_ids: ["cnt_007", "cnt_008"],
  },
  {
    id: "camp_006",
    name: "夏季キャンプ早割キャンペーン",
    objective: "acquisition",
    start_date: "2026-04-01",
    end_date: "2026-06-30",
    status: "planning",
    content_ids: [],
  },
];

export const sampleContents: ContentPackage[] = [
  {
    campaign_id: "camp_001",
    content_id: "cnt_001",
    version: 1,
    status: "approved",
    info_classification: "public",
    objective: "acquisition",
    funnel_stage: "awareness",
    persona: ["academy_student"],
    title: "スポーツ栄養学の基礎：試合前の食事で変わるパフォーマンス",
    summary:
      "試合前72時間の栄養戦略がパフォーマンスに与える影響をエビデンスベースで解説。アカデミー受講を訴求。",
    key_messages: [
      {
        claim: "試合前72時間の炭水化物ローディングにより筋グリコーゲン貯蔵量が最大2倍になる可能性が示されている",
        evidence: [
          {
            id: "ev_001",
            type: "citation",
            source: "Hawley et al., Sports Med, 1997",
            confidence: "high",
          },
        ],
        supervised_by: "管理栄養士 田中",
      },
    ],
    disclaimers: [
      "※個人差があります。具体的な食事計画は専門家にご相談ください。",
    ],
    do_not_say: ["絶対", "必ず痩せる", "治る", "医学的に証明"],
    risk_flags: [],
    cta_set: [
      {
        label: "無料体験に申し込む",
        url_template: "https://fam.example.com/academy/trial?utm_source={{source}}&utm_medium={{medium}}&utm_campaign={{campaign}}",
        type: "signup",
      },
    ],
    utm_plan: {
      source: "instagram",
      medium: "social",
      campaign: "spring_academy_2026",
    },
    asset_plan: [
      {
        asset_type: "video",
        purpose: "reels_main",
        width: 1080,
        height: 1920,
        template_id: "tpl_reels_edu",
      },
      {
        asset_type: "image",
        purpose: "feed_carousel",
        width: 1080,
        height: 1080,
        template_id: "tpl_carousel_5",
      },
    ],
    target_channels: ["instagram_reels", "instagram_feed", "note", "line"],
    created_at: "2026-02-01T09:00:00Z",
    updated_at: "2026-02-01T14:00:00Z",
    created_by: "planner_suzuki",
  },
  {
    campaign_id: "camp_001",
    content_id: "cnt_002",
    version: 1,
    status: "review",
    info_classification: "public",
    objective: "acquisition",
    funnel_stage: "interest",
    persona: ["academy_student"],
    title: "試合前にやりがちなNG食事3選",
    summary: "よくある間違いを具体例で紹介し、正しいアプローチを訴求。",
    key_messages: [],
    disclaimers: ["※個人差があります。"],
    do_not_say: ["絶対", "必ず"],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "instagram", medium: "social", campaign: "spring_academy_2026" },
    asset_plan: [],
    target_channels: ["instagram_feed"],
    created_at: "2026-02-02T10:00:00Z",
    updated_at: "2026-02-02T14:00:00Z",
    created_by: "田中",
  },
  {
    campaign_id: "camp_002",
    content_id: "cnt_003",
    version: 1,
    status: "approved",
    info_classification: "public",
    objective: "retention",
    funnel_stage: "loyalty",
    persona: ["b2c_subscriber"],
    title: "プロテイン定期便：今月のおすすめレシピ",
    summary: "定期便ユーザー向けにプロテインを使ったレシピを提案。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "line", medium: "message", campaign: "protein_sub_2026" },
    asset_plan: [],
    target_channels: ["line"],
    created_at: "2026-02-03T09:00:00Z",
    updated_at: "2026-02-03T12:00:00Z",
    created_by: "佐藤",
  },
  {
    campaign_id: "camp_003",
    content_id: "cnt_004",
    version: 1,
    status: "approved",
    info_classification: "public",
    objective: "trust",
    funnel_stage: "consideration",
    persona: ["b2c_subscriber", "academy_student"],
    title: "管理栄養士が教える：エビデンスに基づく栄養指導",
    summary: "管理栄養士監修シリーズの第1弾。科学的根拠に基づいた情報を発信。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "note", medium: "article", campaign: "dietitian_series" },
    asset_plan: [],
    target_channels: ["note"],
    created_at: "2026-02-05T09:00:00Z",
    updated_at: "2026-02-05T15:00:00Z",
    created_by: "田中",
  },
  {
    campaign_id: "camp_003",
    content_id: "cnt_005",
    version: 1,
    status: "draft",
    info_classification: "public",
    objective: "trust",
    funnel_stage: "awareness",
    persona: ["b2c_subscriber"],
    title: "タンパク質摂取の適正量とは？",
    summary: "タンパク質の過剰摂取リスクと適正量について解説。",
    key_messages: [],
    disclaimers: [],
    do_not_say: ["必ず効果が出る"],
    risk_flags: ["要法務確認"],
    cta_set: [],
    utm_plan: { source: "instagram", medium: "social", campaign: "dietitian_series" },
    asset_plan: [],
    target_channels: ["instagram_reels"],
    created_at: "2026-02-06T10:00:00Z",
    updated_at: "2026-02-06T14:00:00Z",
    created_by: "鈴木",
  },
  {
    campaign_id: "camp_005",
    content_id: "cnt_007",
    version: 1,
    status: "approved",
    info_classification: "public",
    objective: "event",
    funnel_stage: "conversion",
    persona: ["academy_student", "b2c_subscriber"],
    title: "4月スポーツ栄養セミナー LP",
    summary: "セミナー集客用LP。無料体験を訴求。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "lp", medium: "web", campaign: "seminar_apr_2026" },
    asset_plan: [],
    target_channels: ["event_lp", "instagram_stories"],
    created_at: "2026-02-08T09:00:00Z",
    updated_at: "2026-02-08T15:00:00Z",
    created_by: "佐藤",
  },
  {
    campaign_id: "camp_005",
    content_id: "cnt_008",
    version: 1,
    status: "draft",
    info_classification: "public",
    objective: "event",
    funnel_stage: "awareness",
    persona: ["b2c_subscriber"],
    title: "セミナー告知LINE配信",
    summary: "LINE配信でセミナー告知を行い、LP誘導を狙う。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "line", medium: "message", campaign: "seminar_apr_2026" },
    asset_plan: [],
    target_channels: ["line"],
    created_at: "2026-02-09T10:00:00Z",
    updated_at: "2026-02-09T12:00:00Z",
    created_by: "鈴木",
  },
];

export const sampleVariants: ChannelVariant[] = [
  {
    id: "var_001",
    content_id: "cnt_001",
    channel: "instagram_reels",
    status: "approved",
    body: {
      hook: "試合前の食事、なんとなくで決めてませんか？",
      problem: "多くの選手が試合直前の食事だけを意識しがち。",
      cta: "プロフィールのリンクから詳細へ！",
      caption: "試合前72時間で差がつく🍙 カーボローディングの科学",
      hashtags: ["スポーツ栄養", "試合前食事", "FAMアカデミー"],
    },
    scheduled_at: "2026-03-05T12:00:00Z",
    assignee: "田中",
  },
  {
    id: "var_002",
    content_id: "cnt_001",
    channel: "line",
    status: "draft",
    body: {
      delivery_type: "broadcast",
      message_text: "【NEW】試合前の食事、なんとなくで決めてませんか？\n科学的な栄養戦略を学べる無料体験、受付中！",
      cta_label: "詳細はこちら",
    },
    scheduled_at: "2026-03-07T10:00:00Z",
    assignee: "鈴木",
  },
  {
    id: "var_003",
    content_id: "cnt_002",
    channel: "instagram_feed",
    status: "review",
    body: {
      slide1_cover: "知らないと損する\n試合前食事の3つのNG",
      caption: "試合前の食事戦略、正しく知っていますか？",
    },
    scheduled_at: "2026-03-10T12:00:00Z",
    assignee: "田中",
  },
  {
    id: "var_004",
    content_id: "cnt_003",
    channel: "line",
    status: "approved",
    body: {
      delivery_type: "step",
      message_text: "いつもご利用ありがとうございます！プロテイン定期便、今月も届きます。",
      cta_label: "マイページで確認",
    },
    scheduled_at: "2026-02-15T09:00:00Z",
    assignee: "佐藤",
  },
  {
    id: "var_005",
    content_id: "cnt_004",
    channel: "note",
    status: "approved",
    body: {
      title_option1: "管理栄養士が教える：エビデンスに基づく栄養指導のポイント",
      lead: "科学的根拠に基づいた栄養指導の実践について解説します。",
      tags: ["管理栄養士", "エビデンス", "栄養指導"],
    },
    scheduled_at: "2026-02-20T08:00:00Z",
    assignee: "田中",
  },
  {
    id: "var_006",
    content_id: "cnt_005",
    channel: "instagram_reels",
    status: "draft",
    body: {
      hook: "「タンパク質は多ければ多いほどいい」は本当？",
      cta: "答えはプロフィールのリンクから",
    },
    scheduled_at: "2026-03-01T12:00:00Z",
    assignee: "鈴木",
  },
  {
    id: "var_007",
    content_id: "cnt_007",
    channel: "event_lp",
    status: "approved",
    body: {
      title: "スポーツ栄養セミナー 無料体験",
      event_date: "2026-04-10T14:00",
      event_location: "オンライン（Zoom）",
      cta_text: "今すぐ申し込む",
    },
    scheduled_at: "2026-03-25T10:00:00Z",
    assignee: "佐藤",
  },
  {
    id: "var_008",
    content_id: "cnt_007",
    channel: "instagram_stories",
    status: "review",
    body: {
      story_type: "countdown",
      countdown_title: "セミナーまであと...",
    },
    scheduled_at: "2026-04-03T12:00:00Z",
    assignee: "田中",
  },
  {
    id: "var_009",
    content_id: "cnt_008",
    channel: "line",
    status: "draft",
    body: {
      delivery_type: "broadcast",
      message_text: "【4月セミナー】スポーツ栄養の最新トレンドを学びませんか？無料です！",
      cta_label: "申し込みはこちら",
    },
    scheduled_at: "2026-03-28T10:00:00Z",
    assignee: "鈴木",
  },
];

export const sampleReviews: ReviewRecord[] = [
  {
    id: "rev_001",
    content_id: "cnt_001",
    reviewer: "管理栄養士 田中",
    role: "supervisor",
    decision: "approved",
    comment: "エビデンスの引用が適切。免責も問題なし。",
    labels: ["evidence_ok", "disclaimer_ok"],
    created_at: "2026-02-01T13:00:00Z",
  },
  {
    id: "rev_002",
    content_id: "cnt_002",
    reviewer: "法務 山本",
    role: "legal",
    decision: "revision_requested",
    comment: "景表法の観点で「最大2倍」の表現を要修正。根拠資料の追加をお願いします。",
    labels: ["legal_check"],
    created_at: "2026-02-02T10:30:00Z",
  },
  {
    id: "rev_008",
    content_id: "cnt_002",
    reviewer: "田中",
    role: "supervisor",
    decision: "approved",
    comment: "承知しました。Hawley et al.の原著を確認し、表現を「研究では最大2倍程度の増加が報告されている」に修正します。",
    labels: [],
    created_at: "2026-02-02T11:15:00Z",
    reply_to: "rev_002",
  },
  {
    id: "rev_009",
    content_id: "cnt_002",
    reviewer: "法務 山本",
    role: "legal",
    decision: "approved",
    comment: "修正案確認しました。その表現であれば問題ありません。",
    labels: ["legal_ok"],
    created_at: "2026-02-02T14:00:00Z",
    reply_to: "rev_008",
  },
  {
    id: "rev_003",
    content_id: "cnt_003",
    reviewer: "ブランド 佐藤",
    role: "brand",
    decision: "approved",
    comment: "トーン&マナー問題なし。ブランドガイドラインに準拠。",
    labels: ["brand_ok"],
    created_at: "2026-02-03T09:00:00Z",
  },
  {
    id: "rev_004",
    content_id: "cnt_004",
    reviewer: "管理栄養士 田中",
    role: "supervisor",
    decision: "approved",
    comment: "栄養指導の内容が正確。参考文献もOK。",
    labels: ["evidence_ok"],
    created_at: "2026-02-05T11:00:00Z",
  },
  {
    id: "rev_005",
    content_id: "cnt_005",
    reviewer: "法務 山本",
    role: "legal",
    decision: "revision_requested",
    comment: "「必ず効果が出る」の表現はNG。修正をお願いします。",
    labels: ["legal_check"],
    created_at: "2026-02-06T14:00:00Z",
  },
  {
    id: "rev_010",
    content_id: "cnt_005",
    reviewer: "鈴木",
    role: "brand",
    decision: "approved",
    comment: "承知しました。「効果には個人差があります」の注釈を追加する形でいかがでしょうか？",
    labels: [],
    created_at: "2026-02-06T15:30:00Z",
    reply_to: "rev_005",
  },
  {
    id: "rev_011",
    content_id: "cnt_005",
    reviewer: "法務 山本",
    role: "legal",
    decision: "approved",
    comment: "それで大丈夫です。修正版のレビューをお待ちしています。",
    labels: [],
    created_at: "2026-02-06T16:00:00Z",
    reply_to: "rev_010",
  },
  {
    id: "rev_006",
    content_id: "cnt_007",
    reviewer: "ブランド 佐藤",
    role: "brand",
    decision: "approved",
    comment: "セミナーLPのデザイン・文言ともに問題なし。",
    labels: ["brand_ok"],
    created_at: "2026-02-08T10:00:00Z",
  },
  {
    id: "rev_012",
    content_id: "cnt_007",
    reviewer: "田中",
    role: "supervisor",
    decision: "approved",
    comment: "CTAボタンの色はもう少し目立つ色がいいかもしれません。",
    labels: [],
    created_at: "2026-02-08T11:00:00Z",
    reply_to: "rev_006",
  },
  {
    id: "rev_013",
    content_id: "cnt_007",
    reviewer: "ブランド 佐藤",
    role: "brand",
    decision: "approved",
    comment: "ご指摘ありがとうございます。オレンジ系に変更しました！",
    labels: [],
    created_at: "2026-02-08T14:00:00Z",
    reply_to: "rev_012",
  },
  {
    id: "rev_007",
    content_id: "cnt_007",
    reviewer: "管理栄養士 田中",
    role: "supervisor",
    decision: "approved",
    comment: "セミナー内容の監修完了。",
    labels: ["evidence_ok", "supervisor_ok"],
    created_at: "2026-02-08T15:00:00Z",
  },
];

export const samplePublishJobs: PublishJob[] = [
  {
    id: "pj_001",
    content_id: "cnt_001",
    channel: "instagram_reels",
    status: "queued",
    scheduled_at: "2026-03-05T12:00:00Z",
  },
];

export const sampleMetrics: MetricDaily[] = [
  {
    id: "m_001",
    content_id: "cnt_001",
    channel: "instagram_reels",
    date: "2026-03-05",
    impressions: 12500,
    engagements: 890,
    clicks: 210,
    conversions: 18,
    custom: { saves: 145, shares: 67, completion_rate: 0.42 },
  },
];
