import type {
  Campaign,
  ContentPackage,
  ChannelVariant,
  ReviewRecord,
  PublishJob,
  MetricDaily,
} from "@/types/content_package";

export const sampleCampaigns: Campaign[] = [
  {
    id: "camp_001",
    name: "春季アカデミー募集キャンペーン",
    objective: "acquisition",
    start_date: "2026-03-01",
    end_date: "2026-04-30",
    status: "active",
    content_ids: ["cnt_001", "cnt_002"],
  },
  {
    id: "camp_002",
    name: "プロテインサブスク継続施策",
    objective: "retention",
    start_date: "2026-02-01",
    end_date: "2026-03-31",
    status: "active",
    content_ids: ["cnt_003"],
  },
  {
    id: "camp_003",
    name: "管理栄養士監修シリーズ",
    objective: "trust",
    start_date: "2026-02-10",
    end_date: "2026-05-31",
    status: "active",
    content_ids: ["cnt_004", "cnt_005"],
  },
  {
    id: "camp_004",
    name: "管理栄養士インターン募集",
    objective: "recruitment",
    start_date: "2026-03-15",
    end_date: "2026-04-15",
    status: "planning",
    content_ids: ["cnt_006"],
  },
  {
    id: "camp_005",
    name: "スポーツ栄養セミナー 4月開催",
    objective: "event",
    start_date: "2026-03-20",
    end_date: "2026-04-20",
    status: "active",
    content_ids: ["cnt_007", "cnt_008"],
  },
  {
    id: "camp_006",
    name: "夏季キャンプ早割キャンペーン",
    objective: "acquisition",
    start_date: "2026-04-01",
    end_date: "2026-06-30",
    status: "planning",
    content_ids: ["cnt_009", "cnt_010"],
  },
  // 追加キャンペーン
  {
    id: "camp_007",
    name: "新生活応援プロテインキャンペーン",
    objective: "acquisition",
    start_date: "2026-03-01",
    end_date: "2026-04-15",
    status: "active",
    content_ids: ["cnt_011", "cnt_012"],
  },
  {
    id: "camp_008",
    name: "アスリート向け栄養相談サービス",
    objective: "trust",
    start_date: "2026-02-15",
    end_date: "2026-05-15",
    status: "active",
    content_ids: ["cnt_013", "cnt_014"],
  },
  {
    id: "camp_009",
    name: "法人向け健康経営プラン",
    objective: "acquisition",
    start_date: "2026-03-01",
    end_date: "2026-06-30",
    status: "active",
    content_ids: ["cnt_015", "cnt_016"],
  },
  {
    id: "camp_010",
    name: "夏のダイエットチャレンジ",
    objective: "retention",
    start_date: "2026-05-01",
    end_date: "2026-07-31",
    status: "planning",
    content_ids: ["cnt_017"],
  },
  {
    id: "camp_011",
    name: "ジュニアアスリート育成プログラム",
    objective: "event",
    start_date: "2026-04-01",
    end_date: "2026-08-31",
    status: "active",
    content_ids: ["cnt_018", "cnt_019"],
  },
  {
    id: "camp_012",
    name: "秋季オンラインセミナーシリーズ",
    objective: "event",
    start_date: "2026-09-01",
    end_date: "2026-11-30",
    status: "planning",
    content_ids: ["cnt_020"],
  },
  {
    id: "camp_013",
    name: "シニア向け栄養サポート",
    objective: "trust",
    start_date: "2026-02-01",
    end_date: "2026-12-31",
    status: "active",
    content_ids: ["cnt_021", "cnt_022"],
  },
  {
    id: "camp_014",
    name: "新商品プロテインバー発売記念",
    objective: "acquisition",
    start_date: "2026-04-15",
    end_date: "2026-05-31",
    status: "planning",
    content_ids: ["cnt_023"],
  },
];

export const sampleContents: ContentPackage[] = [
  {
    campaign_id: "camp_001",
    content_id: "cnt_001",
    version: 1,
    status: "approved",
    info_classification: "public",
    objective: "acquisition",
    funnel_stage: "awareness",
    persona: ["academy_student"],
    title: "スポーツ栄養学の基礎：試合前の食事で変わるパフォーマンス",
    summary:
      "試合前72時間の栄養戦略がパフォーマンスに与える影響をエビデンスベースで解説。アカデミー受講を訴求。",
    key_messages: [
      {
        claim: "試合前72時間の炭水化物ローディングにより筋グリコーゲン貯蔵量が最大2倍になる可能性が示されている",
        evidence: [
          {
            id: "ev_001",
            type: "citation",
            source: "Hawley et al., Sports Med, 1997",
            confidence: "high",
          },
        ],
        supervised_by: "管理栄養士 田中",
      },
    ],
    disclaimers: [
      "※個人差があります。具体的な食事計画は専門家にご相談ください。",
    ],
    do_not_say: ["絶対", "必ず痩せる", "治る", "医学的に証明"],
    risk_flags: [],
    cta_set: [
      {
        label: "無料体験に申し込む",
        url_template: "https://fam.example.com/academy/trial?utm_source={{source}}&utm_medium={{medium}}&utm_campaign={{campaign}}",
        type: "signup",
      },
    ],
    utm_plan: {
      source: "instagram",
      medium: "social",
      campaign: "spring_academy_2026",
    },
    asset_plan: [
      {
        asset_type: "video",
        purpose: "reels_main",
        width: 1080,
        height: 1920,
        template_id: "tpl_reels_edu",
      },
      {
        asset_type: "image",
        purpose: "feed_carousel",
        width: 1080,
        height: 1080,
        template_id: "tpl_carousel_5",
      },
    ],
    target_channels: ["instagram_reels", "instagram_feed", "note", "line"],
    created_at: "2026-02-01T09:00:00Z",
    updated_at: "2026-02-01T14:00:00Z",
    created_by: "田中",
    review_requested_to: "佐藤",
    review_requested_at: "2026-02-01T10:00:00Z",
  },
  {
    campaign_id: "camp_001",
    content_id: "cnt_002",
    version: 1,
    status: "review",
    info_classification: "public",
    objective: "acquisition",
    funnel_stage: "interest",
    persona: ["academy_student"],
    title: "試合前にやりがちなNG食事3選",
    summary: "よくある間違いを具体例で紹介し、正しいアプローチを訴求。",
    key_messages: [],
    disclaimers: ["※個人差があります。"],
    do_not_say: ["絶対", "必ず"],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "instagram", medium: "social", campaign: "spring_academy_2026" },
    asset_plan: [],
    target_channels: ["instagram_feed"],
    created_at: "2026-02-02T10:00:00Z",
    updated_at: "2026-02-02T14:00:00Z",
    created_by: "田中",
    review_requested_to: "鈴木",
    review_requested_at: "2026-02-02T11:00:00Z",
  },
  {
    campaign_id: "camp_002",
    content_id: "cnt_003",
    version: 1,
    status: "approved",
    info_classification: "public",
    objective: "retention",
    funnel_stage: "loyalty",
    persona: ["b2c_subscriber"],
    title: "プロテイン定期便：今月のおすすめレシピ",
    summary: "定期便ユーザー向けにプロテインを使ったレシピを提案。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "line", medium: "message", campaign: "protein_sub_2026" },
    asset_plan: [],
    target_channels: ["line"],
    created_at: "2026-02-03T09:00:00Z",
    updated_at: "2026-02-03T12:00:00Z",
    created_by: "佐藤",
  },
  {
    campaign_id: "camp_003",
    content_id: "cnt_004",
    version: 1,
    status: "approved",
    info_classification: "public",
    objective: "trust",
    funnel_stage: "consideration",
    persona: ["b2c_subscriber", "academy_student"],
    title: "管理栄養士が教える：エビデンスに基づく栄養指導",
    summary: "管理栄養士監修シリーズの第1弾。科学的根拠に基づいた情報を発信。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "note", medium: "article", campaign: "dietitian_series" },
    asset_plan: [],
    target_channels: ["note"],
    created_at: "2026-02-05T09:00:00Z",
    updated_at: "2026-02-05T15:00:00Z",
    created_by: "田中",
  },
  {
    campaign_id: "camp_003",
    content_id: "cnt_005",
    version: 1,
    status: "draft",
    info_classification: "public",
    objective: "trust",
    funnel_stage: "awareness",
    persona: ["b2c_subscriber"],
    title: "タンパク質摂取の適正量とは？",
    summary: "タンパク質の過剰摂取リスクと適正量について解説。",
    key_messages: [],
    disclaimers: [],
    do_not_say: ["必ず効果が出る"],
    risk_flags: ["要法務確認"],
    cta_set: [],
    utm_plan: { source: "instagram", medium: "social", campaign: "dietitian_series" },
    asset_plan: [],
    target_channels: ["instagram_reels"],
    created_at: "2026-02-06T10:00:00Z",
    updated_at: "2026-02-06T14:00:00Z",
    created_by: "鈴木",
    review_requested_to: "田中",
    review_requested_at: "2026-02-06T11:00:00Z",
  },
  {
    campaign_id: "camp_004",
    content_id: "cnt_006",
    version: 1,
    status: "draft",
    info_classification: "internal",
    objective: "recruitment",
    funnel_stage: "awareness",
    persona: ["academy_student"],
    title: "管理栄養士インターン募集要項",
    summary: "インターン募集の詳細と応募方法を案内。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "direct", medium: "web", campaign: "intern_2026" },
    asset_plan: [],
    target_channels: ["note"],
    created_at: "2026-02-07T09:00:00Z",
    updated_at: "2026-02-07T12:00:00Z",
    created_by: "佐藤",
  },
  {
    campaign_id: "camp_005",
    content_id: "cnt_007",
    version: 1,
    status: "approved",
    info_classification: "public",
    objective: "event",
    funnel_stage: "conversion",
    persona: ["academy_student", "b2c_subscriber"],
    title: "4月スポーツ栄養セミナー LP",
    summary: "セミナー集客用LP。無料体験を訴求。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "lp", medium: "web", campaign: "seminar_apr_2026" },
    asset_plan: [],
    target_channels: ["event_lp", "instagram_stories"],
    created_at: "2026-02-08T09:00:00Z",
    updated_at: "2026-02-08T15:00:00Z",
    created_by: "佐藤",
  },
  {
    campaign_id: "camp_005",
    content_id: "cnt_008",
    version: 1,
    status: "draft",
    info_classification: "public",
    objective: "event",
    funnel_stage: "awareness",
    persona: ["b2c_subscriber"],
    title: "セミナー告知LINE配信",
    summary: "LINE配信でセミナー告知を行い、LP誘導を狙う。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "line", medium: "message", campaign: "seminar_apr_2026" },
    asset_plan: [],
    target_channels: ["line"],
    created_at: "2026-02-09T10:00:00Z",
    updated_at: "2026-02-09T12:00:00Z",
    created_by: "鈴木",
  },
  // 追加コンテンツ
  {
    campaign_id: "camp_006",
    content_id: "cnt_009",
    version: 1,
    status: "draft",
    info_classification: "public",
    objective: "acquisition",
    funnel_stage: "awareness",
    persona: ["academy_student"],
    title: "夏季キャンプ2026：スポーツ栄養集中講座",
    summary: "夏季キャンプの概要と早割特典を紹介。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "instagram", medium: "social", campaign: "summer_camp_2026" },
    asset_plan: [],
    target_channels: ["instagram_reels", "instagram_feed"],
    created_at: "2026-02-10T09:00:00Z",
    updated_at: "2026-02-10T12:00:00Z",
    created_by: "田中",
  },
  {
    campaign_id: "camp_006",
    content_id: "cnt_010",
    version: 1,
    status: "review",
    info_classification: "public",
    objective: "acquisition",
    funnel_stage: "interest",
    persona: ["academy_student"],
    title: "昨年参加者の声：夏季キャンプ体験談",
    summary: "過去参加者のインタビューと成果を紹介。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "note", medium: "article", campaign: "summer_camp_2026" },
    asset_plan: [],
    target_channels: ["note"],
    created_at: "2026-02-11T09:00:00Z",
    updated_at: "2026-02-11T14:00:00Z",
    created_by: "佐藤",
    review_requested_to: "田中",
    review_requested_at: "2026-02-11T10:00:00Z",
  },
  {
    campaign_id: "camp_007",
    content_id: "cnt_011",
    version: 1,
    status: "approved",
    info_classification: "public",
    objective: "acquisition",
    funnel_stage: "awareness",
    persona: ["b2c_subscriber"],
    title: "新生活にプロテインを始めよう",
    summary: "新社会人・新大学生向けにプロテイン習慣の始め方を紹介。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "instagram", medium: "social", campaign: "spring_protein_2026" },
    asset_plan: [],
    target_channels: ["instagram_reels", "line"],
    created_at: "2026-02-12T09:00:00Z",
    updated_at: "2026-02-12T15:00:00Z",
    created_by: "鈴木",
  },
  {
    campaign_id: "camp_007",
    content_id: "cnt_012",
    version: 1,
    status: "review",
    info_classification: "public",
    objective: "acquisition",
    funnel_stage: "conversion",
    persona: ["b2c_subscriber"],
    title: "初回限定30%OFFキャンペーン告知",
    summary: "新規購入者向けの割引キャンペーンを告知。",
    key_messages: [],
    disclaimers: ["※初回購入の方限定"],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "line", medium: "message", campaign: "spring_protein_2026" },
    asset_plan: [],
    target_channels: ["line", "instagram_stories"],
    created_at: "2026-02-13T10:00:00Z",
    updated_at: "2026-02-13T14:00:00Z",
    created_by: "佐藤",
    review_requested_to: "鈴木",
    review_requested_at: "2026-02-13T11:00:00Z",
  },
  {
    campaign_id: "camp_008",
    content_id: "cnt_013",
    version: 1,
    status: "approved",
    info_classification: "public",
    objective: "trust",
    funnel_stage: "consideration",
    persona: ["academy_student"],
    title: "プロアスリートの栄養管理事例",
    summary: "実際のプロアスリートがどのように栄養管理を行っているかを紹介。",
    key_messages: [],
    disclaimers: ["※個人差があります"],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "note", medium: "article", campaign: "athlete_nutrition_2026" },
    asset_plan: [],
    target_channels: ["note", "instagram_feed"],
    created_at: "2026-02-14T09:00:00Z",
    updated_at: "2026-02-14T16:00:00Z",
    created_by: "田中",
  },
  {
    campaign_id: "camp_008",
    content_id: "cnt_014",
    version: 1,
    status: "draft",
    info_classification: "public",
    objective: "trust",
    funnel_stage: "awareness",
    persona: ["academy_student"],
    title: "オンライン栄養相談サービス紹介",
    summary: "アスリート向けオンライン栄養相談サービスの概要。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "lp", medium: "web", campaign: "athlete_nutrition_2026" },
    asset_plan: [],
    target_channels: ["event_lp"],
    created_at: "2026-02-15T09:00:00Z",
    updated_at: "2026-02-15T12:00:00Z",
    created_by: "鈴木",
  },
  {
    campaign_id: "camp_009",
    content_id: "cnt_015",
    version: 1,
    status: "approved",
    info_classification: "public",
    objective: "acquisition",
    funnel_stage: "awareness",
    persona: ["b2b_team"],
    title: "企業の健康経営をサポートする栄養プログラム",
    summary: "法人向け健康経営支援サービスの紹介。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "direct", medium: "email", campaign: "corporate_health_2026" },
    asset_plan: [],
    target_channels: ["note"],
    created_at: "2026-02-16T09:00:00Z",
    updated_at: "2026-02-16T15:00:00Z",
    created_by: "佐藤",
  },
  {
    campaign_id: "camp_009",
    content_id: "cnt_016",
    version: 1,
    status: "review",
    info_classification: "public",
    objective: "acquisition",
    funnel_stage: "conversion",
    persona: ["b2b_team"],
    title: "法人プラン資料請求ページ",
    summary: "法人向けプランの詳細と資料請求フォーム。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "lp", medium: "web", campaign: "corporate_health_2026" },
    asset_plan: [],
    target_channels: ["event_lp"],
    created_at: "2026-02-17T10:00:00Z",
    updated_at: "2026-02-17T14:00:00Z",
    created_by: "田中",
    review_requested_to: "佐藤",
    review_requested_at: "2026-02-17T11:00:00Z",
  },
  {
    campaign_id: "camp_010",
    content_id: "cnt_017",
    version: 1,
    status: "draft",
    info_classification: "public",
    objective: "retention",
    funnel_stage: "loyalty",
    persona: ["b2c_subscriber"],
    title: "夏に向けた健康的なダイエット法",
    summary: "リバウンドしない健康的なダイエットの方法を紹介。",
    key_messages: [],
    disclaimers: ["※個人差があります"],
    do_not_say: ["必ず痩せる", "短期間で"],
    risk_flags: ["要法務確認"],
    cta_set: [],
    utm_plan: { source: "instagram", medium: "social", campaign: "summer_diet_2026" },
    asset_plan: [],
    target_channels: ["instagram_reels", "note"],
    created_at: "2026-02-18T09:00:00Z",
    updated_at: "2026-02-18T12:00:00Z",
    created_by: "鈴木",
  },
  {
    campaign_id: "camp_011",
    content_id: "cnt_018",
    version: 1,
    status: "approved",
    info_classification: "public",
    objective: "event",
    funnel_stage: "awareness",
    persona: ["academy_student"],
    title: "ジュニアアスリート向け栄養セミナー",
    summary: "小中学生向けのスポーツ栄養セミナーの告知。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "lp", medium: "web", campaign: "junior_athlete_2026" },
    asset_plan: [],
    target_channels: ["event_lp", "instagram_feed"],
    created_at: "2026-02-19T09:00:00Z",
    updated_at: "2026-02-19T15:00:00Z",
    created_by: "佐藤",
  },
  {
    campaign_id: "camp_011",
    content_id: "cnt_019",
    version: 1,
    status: "review",
    info_classification: "public",
    objective: "event",
    funnel_stage: "conversion",
    persona: ["academy_student"],
    title: "保護者向け：子どもの栄養管理ガイド",
    summary: "保護者向けに子どものスポーツ栄養の基礎を解説。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "note", medium: "article", campaign: "junior_athlete_2026" },
    asset_plan: [],
    target_channels: ["note"],
    created_at: "2026-02-20T09:00:00Z",
    updated_at: "2026-02-20T14:00:00Z",
    created_by: "田中",
    review_requested_to: "佐藤",
    review_requested_at: "2026-02-20T10:00:00Z",
  },
  {
    campaign_id: "camp_012",
    content_id: "cnt_020",
    version: 1,
    status: "draft",
    info_classification: "public",
    objective: "event",
    funnel_stage: "awareness",
    persona: ["b2c_subscriber", "academy_student"],
    title: "秋のオンラインセミナーシリーズ予告",
    summary: "9月から開催するオンラインセミナーシリーズの予告。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "line", medium: "message", campaign: "autumn_seminar_2026" },
    asset_plan: [],
    target_channels: ["line", "instagram_stories"],
    created_at: "2026-02-21T09:00:00Z",
    updated_at: "2026-02-21T12:00:00Z",
    created_by: "鈴木",
  },
  {
    campaign_id: "camp_013",
    content_id: "cnt_021",
    version: 1,
    status: "approved",
    info_classification: "public",
    objective: "trust",
    funnel_stage: "awareness",
    persona: ["b2c_subscriber"],
    title: "シニア世代の筋力維持と栄養",
    summary: "高齢者向けに筋力維持のための栄養アドバイスを紹介。",
    key_messages: [],
    disclaimers: ["※かかりつけ医にご相談ください"],
    do_not_say: ["治る", "必ず"],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "note", medium: "article", campaign: "senior_nutrition_2026" },
    asset_plan: [],
    target_channels: ["note"],
    created_at: "2026-02-22T09:00:00Z",
    updated_at: "2026-02-22T15:00:00Z",
    created_by: "佐藤",
  },
  {
    campaign_id: "camp_013",
    content_id: "cnt_022",
    version: 1,
    status: "review",
    info_classification: "public",
    objective: "trust",
    funnel_stage: "consideration",
    persona: ["b2c_subscriber"],
    title: "シニア向けプロテイン選び方ガイド",
    summary: "高齢者に適したプロテインの選び方を解説。",
    key_messages: [],
    disclaimers: ["※アレルギーにご注意ください"],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "line", medium: "message", campaign: "senior_nutrition_2026" },
    asset_plan: [],
    target_channels: ["line", "note"],
    created_at: "2026-02-23T09:00:00Z",
    updated_at: "2026-02-23T14:00:00Z",
    created_by: "田中",
    review_requested_to: "鈴木",
    review_requested_at: "2026-02-23T10:00:00Z",
  },
  {
    campaign_id: "camp_014",
    content_id: "cnt_023",
    version: 1,
    status: "draft",
    info_classification: "public",
    objective: "acquisition",
    funnel_stage: "awareness",
    persona: ["b2c_subscriber"],
    title: "新商品：プロテインバー発売記念",
    summary: "新発売のプロテインバーの特徴と発売記念キャンペーンを告知。",
    key_messages: [],
    disclaimers: [],
    do_not_say: [],
    risk_flags: [],
    cta_set: [],
    utm_plan: { source: "instagram", medium: "social", campaign: "protein_bar_launch_2026" },
    asset_plan: [],
    target_channels: ["instagram_reels", "instagram_stories", "line"],
    created_at: "2026-02-24T09:00:00Z",
    updated_at: "2026-02-24T12:00:00Z",
    created_by: "鈴木",
  },
];

export const sampleVariants: ChannelVariant[] = [
  {
    id: "var_001",
    content_id: "cnt_001",
    channel: "instagram_reels",
    status: "approved",
    body: {
      hook: "試合前の食事、なんとなくで決めてませんか？",
      problem: "多くの選手が試合直前の食事だけを意識しがち。",
      cta: "プロフィールのリンクから詳細へ！",
      caption: "試合前72時間で差がつく🍙 カーボローディングの科学",
      hashtags: ["スポーツ栄養", "試合前食事", "FAMアカデミー"],
    },
    scheduled_at: "2026-03-05T12:00:00Z",
    assignee: "田中",
  },
  {
    id: "var_002",
    content_id: "cnt_001",
    channel: "line",
    status: "draft",
    body: {
      delivery_type: "broadcast",
      message_text: "【NEW】試合前の食事、なんとなくで決めてませんか？\n科学的な栄養戦略を学べる無料体験、受付中！",
      cta_label: "詳細はこちら",
    },
    scheduled_at: "2026-03-07T10:00:00Z",
    assignee: "鈴木",
  },
  {
    id: "var_003",
    content_id: "cnt_002",
    channel: "instagram_feed",
    status: "review",
    body: {
      slide1_cover: "知らないと損する\n試合前食事の3つのNG",
      caption: "試合前の食事戦略、正しく知っていますか？",
    },
    scheduled_at: "2026-03-10T12:00:00Z",
    assignee: "田中",
  },
  {
    id: "var_004",
    content_id: "cnt_003",
    channel: "line",
    status: "approved",
    body: {
      delivery_type: "step",
      message_text: "いつもご利用ありがとうございます！プロテイン定期便、今月も届きます。",
      cta_label: "マイページで確認",
    },
    scheduled_at: "2026-02-15T09:00:00Z",
    assignee: "佐藤",
  },
  {
    id: "var_005",
    content_id: "cnt_004",
    channel: "note",
    status: "approved",
    body: {
      title_option1: "管理栄養士が教える：エビデンスに基づく栄養指導のポイント",
      lead: "科学的根拠に基づいた栄養指導の実践について解説します。",
      tags: ["管理栄養士", "エビデンス", "栄養指導"],
    },
    scheduled_at: "2026-02-20T08:00:00Z",
    assignee: "田中",
  },
  {
    id: "var_006",
    content_id: "cnt_005",
    channel: "instagram_reels",
    status: "draft",
    body: {
      hook: "「タンパク質は多ければ多いほどいい」は本当？",
      cta: "答えはプロフィールのリンクから",
    },
    scheduled_at: "2026-03-01T12:00:00Z",
    assignee: "鈴木",
  },
  {
    id: "var_007",
    content_id: "cnt_007",
    channel: "event_lp",
    status: "approved",
    body: {
      title: "スポーツ栄養セミナー 無料体験",
      event_date: "2026-04-10T14:00",
      event_location: "オンライン（Zoom）",
      cta_text: "今すぐ申し込む",
    },
    scheduled_at: "2026-03-25T10:00:00Z",
    assignee: "佐藤",
  },
  {
    id: "var_008",
    content_id: "cnt_007",
    channel: "instagram_stories",
    status: "review",
    body: {
      story_type: "countdown",
      countdown_title: "セミナーまであと...",
    },
    scheduled_at: "2026-04-03T12:00:00Z",
    assignee: "田中",
  },
  {
    id: "var_009",
    content_id: "cnt_008",
    channel: "line",
    status: "draft",
    body: {
      delivery_type: "broadcast",
      message_text: "【4月セミナー】スポーツ栄養の最新トレンドを学びませんか？無料です！",
      cta_label: "申し込みはこちら",
    },
    scheduled_at: "2026-03-28T10:00:00Z",
    assignee: "鈴木",
  },
  // 追加バリアント
  {
    id: "var_010",
    content_id: "cnt_009",
    channel: "instagram_reels",
    status: "draft",
    body: {
      hook: "夏のキャンプで差をつけろ！",
      cta: "早割は4月末まで！",
    },
    scheduled_at: "2026-04-01T12:00:00Z",
    assignee: "田中",
  },
  {
    id: "var_011",
    content_id: "cnt_010",
    channel: "note",
    status: "review",
    body: {
      title_option1: "夏季キャンプ参加者インタビュー",
      lead: "昨年参加した選手たちの声をお届けします",
    },
    scheduled_at: "2026-04-05T08:00:00Z",
    assignee: "佐藤",
  },
  {
    id: "var_012",
    content_id: "cnt_011",
    channel: "instagram_reels",
    status: "approved",
    body: {
      hook: "新生活、プロテインで差をつけよう！",
      cta: "初回30%OFFは今だけ！",
    },
    scheduled_at: "2026-03-15T12:00:00Z",
    assignee: "鈴木",
  },
  {
    id: "var_013",
    content_id: "cnt_011",
    channel: "line",
    status: "approved",
    body: {
      delivery_type: "broadcast",
      message_text: "🌸新生活応援キャンペーン実施中！\n今なら初回30%OFF",
      cta_label: "詳細を見る",
    },
    scheduled_at: "2026-03-15T10:00:00Z",
    assignee: "佐藤",
  },
  {
    id: "var_014",
    content_id: "cnt_012",
    channel: "line",
    status: "review",
    body: {
      delivery_type: "broadcast",
      message_text: "【期間限定】初回購入30%OFFキャンペーン！",
      cta_label: "今すぐ購入",
    },
    scheduled_at: "2026-03-20T10:00:00Z",
    assignee: "田中",
  },
  {
    id: "var_015",
    content_id: "cnt_013",
    channel: "note",
    status: "approved",
    body: {
      title_option1: "トップアスリートの食事管理を公開",
      lead: "実際のプロ選手がどのように栄養管理をしているか",
    },
    scheduled_at: "2026-03-01T08:00:00Z",
    assignee: "田中",
  },
  {
    id: "var_016",
    content_id: "cnt_013",
    channel: "instagram_feed",
    status: "approved",
    body: {
      slide1_cover: "プロアスリートの\n食事管理とは？",
      caption: "トップ選手の栄養管理を徹底解説",
    },
    scheduled_at: "2026-03-05T12:00:00Z",
    assignee: "佐藤",
  },
  {
    id: "var_017",
    content_id: "cnt_015",
    channel: "note",
    status: "approved",
    body: {
      title_option1: "企業の健康経営を支える栄養プログラム",
      lead: "従業員の健康が企業の成長を支える",
    },
    scheduled_at: "2026-03-10T08:00:00Z",
    assignee: "佐藤",
  },
  {
    id: "var_018",
    content_id: "cnt_016",
    channel: "event_lp",
    status: "review",
    body: {
      title: "法人向け健康経営プラン",
      cta_text: "資料請求",
    },
    scheduled_at: "2026-03-15T10:00:00Z",
    assignee: "田中",
  },
  {
    id: "var_019",
    content_id: "cnt_018",
    channel: "event_lp",
    status: "approved",
    body: {
      title: "ジュニアアスリート栄養セミナー",
      event_date: "2026-05-15T10:00",
      event_location: "オンライン（Zoom）",
      cta_text: "申し込む",
    },
    scheduled_at: "2026-04-01T10:00:00Z",
    assignee: "佐藤",
  },
  {
    id: "var_020",
    content_id: "cnt_018",
    channel: "instagram_feed",
    status: "approved",
    body: {
      slide1_cover: "ジュニアアスリート\n栄養セミナー開催！",
      caption: "お子様の成長をサポートする栄養セミナー",
    },
    scheduled_at: "2026-04-05T12:00:00Z",
    assignee: "田中",
  },
  {
    id: "var_021",
    content_id: "cnt_019",
    channel: "note",
    status: "review",
    body: {
      title_option1: "保護者必見！子どもの栄養管理完全ガイド",
      lead: "成長期の子どもに必要な栄養素とは",
    },
    scheduled_at: "2026-04-10T08:00:00Z",
    assignee: "田中",
  },
  {
    id: "var_022",
    content_id: "cnt_021",
    channel: "note",
    status: "approved",
    body: {
      title_option1: "シニア世代のための筋力維持ガイド",
      lead: "いつまでも元気に過ごすための栄養と運動",
    },
    scheduled_at: "2026-03-01T08:00:00Z",
    assignee: "佐藤",
  },
  {
    id: "var_023",
    content_id: "cnt_022",
    channel: "line",
    status: "review",
    body: {
      delivery_type: "segment",
      message_text: "シニア向けプロテインの選び方をご紹介！",
      cta_label: "詳しく見る",
    },
    scheduled_at: "2026-03-10T10:00:00Z",
    assignee: "田中",
  },
  {
    id: "var_024",
    content_id: "cnt_023",
    channel: "instagram_reels",
    status: "draft",
    body: {
      hook: "待望の新商品！プロテインバー登場！",
      cta: "発売記念キャンペーン実施中",
    },
    scheduled_at: "2026-04-20T12:00:00Z",
    assignee: "鈴木",
  },
  {
    id: "var_025",
    content_id: "cnt_023",
    channel: "line",
    status: "draft",
    body: {
      delivery_type: "broadcast",
      message_text: "🎉新商品プロテインバー発売！\n発売記念20%OFFキャンペーン",
      cta_label: "今すぐチェック",
    },
    scheduled_at: "2026-04-20T10:00:00Z",
    assignee: "佐藤",
  },
];

export const sampleReviews: ReviewRecord[] = [
  {
    id: "rev_001",
    content_id: "cnt_001",
    reviewer: "管理栄養士 田中",
    role: "supervisor",
    decision: "approved",
    comment: "エビデンスの引用が適切。免責も問題なし。",
    labels: ["evidence_ok", "disclaimer_ok"],
    created_at: "2026-02-01T13:00:00Z",
  },
  {
    id: "rev_002",
    content_id: "cnt_002",
    reviewer: "法務 山本",
    role: "legal",
    decision: "revision_requested",
    comment: "景表法の観点で「最大2倍」の表現を要修正。根拠資料の追加をお願いします。",
    labels: ["legal_check"],
    created_at: "2026-02-02T10:30:00Z",
  },
  {
    id: "rev_008",
    content_id: "cnt_002",
    reviewer: "田中",
    role: "supervisor",
    decision: "approved",
    comment: "承知しました。Hawley et al.の原著を確認し、表現を「研究では最大2倍程度の増加が報告されている」に修正します。",
    labels: [],
    created_at: "2026-02-02T11:15:00Z",
    reply_to: "rev_002",
  },
  {
    id: "rev_009",
    content_id: "cnt_002",
    reviewer: "法務 山本",
    role: "legal",
    decision: "approved",
    comment: "修正案確認しました。その表現であれば問題ありません。",
    labels: ["legal_ok"],
    created_at: "2026-02-02T14:00:00Z",
    reply_to: "rev_008",
  },
  {
    id: "rev_003",
    content_id: "cnt_003",
    reviewer: "ブランド 佐藤",
    role: "brand",
    decision: "approved",
    comment: "トーン&マナー問題なし。ブランドガイドラインに準拠。",
    labels: ["brand_ok"],
    created_at: "2026-02-03T09:00:00Z",
  },
  {
    id: "rev_004",
    content_id: "cnt_004",
    reviewer: "管理栄養士 田中",
    role: "supervisor",
    decision: "approved",
    comment: "栄養指導の内容が正確。参考文献もOK。",
    labels: ["evidence_ok"],
    created_at: "2026-02-05T11:00:00Z",
  },
  {
    id: "rev_005",
    content_id: "cnt_005",
    reviewer: "法務 山本",
    role: "legal",
    decision: "revision_requested",
    comment: "「必ず効果が出る」の表現はNG。修正をお願いします。",
    labels: ["legal_check"],
    created_at: "2026-02-06T14:00:00Z",
  },
  {
    id: "rev_010",
    content_id: "cnt_005",
    reviewer: "鈴木",
    role: "brand",
    decision: "approved",
    comment: "承知しました。「効果には個人差があります」の注釈を追加する形でいかがでしょうか？",
    labels: [],
    created_at: "2026-02-06T15:30:00Z",
    reply_to: "rev_005",
  },
  {
    id: "rev_011",
    content_id: "cnt_005",
    reviewer: "法務 山本",
    role: "legal",
    decision: "approved",
    comment: "それで大丈夫です。修正版のレビューをお待ちしています。",
    labels: [],
    created_at: "2026-02-06T16:00:00Z",
    reply_to: "rev_010",
  },
  {
    id: "rev_006",
    content_id: "cnt_007",
    reviewer: "ブランド 佐藤",
    role: "brand",
    decision: "approved",
    comment: "セミナーLPのデザイン・文言ともに問題なし。",
    labels: ["brand_ok"],
    created_at: "2026-02-08T10:00:00Z",
  },
  {
    id: "rev_012",
    content_id: "cnt_007",
    reviewer: "田中",
    role: "supervisor",
    decision: "approved",
    comment: "CTAボタンの色はもう少し目立つ色がいいかもしれません。",
    labels: [],
    created_at: "2026-02-08T11:00:00Z",
    reply_to: "rev_006",
  },
  {
    id: "rev_013",
    content_id: "cnt_007",
    reviewer: "ブランド 佐藤",
    role: "brand",
    decision: "approved",
    comment: "ご指摘ありがとうございます。オレンジ系に変更しました！",
    labels: [],
    created_at: "2026-02-08T14:00:00Z",
    reply_to: "rev_012",
  },
  {
    id: "rev_007",
    content_id: "cnt_007",
    reviewer: "管理栄養士 田中",
    role: "supervisor",
    decision: "approved",
    comment: "セミナー内容の監修完了。",
    labels: ["evidence_ok", "supervisor_ok"],
    created_at: "2026-02-08T15:00:00Z",
  },
  // 追加レビュー
  {
    id: "rev_014",
    content_id: "cnt_009",
    reviewer: "ブランド 佐藤",
    role: "brand",
    decision: "approved",
    comment: "夏季キャンプの訴求ポイントがよく伝わる内容です。",
    labels: ["brand_ok"],
    created_at: "2026-02-10T14:00:00Z",
  },
  {
    id: "rev_015",
    content_id: "cnt_010",
    reviewer: "管理栄養士 田中",
    role: "supervisor",
    decision: "revision_requested",
    comment: "参加者の体験談に具体的な数値が含まれていますが、根拠の確認をお願いします。",
    labels: ["evidence_check"],
    created_at: "2026-02-11T15:00:00Z",
  },
  {
    id: "rev_016",
    content_id: "cnt_010",
    reviewer: "佐藤",
    role: "brand",
    decision: "approved",
    comment: "承知しました。数値部分を削除し、定性的な表現に修正します。",
    labels: [],
    created_at: "2026-02-11T16:00:00Z",
    reply_to: "rev_015",
  },
  {
    id: "rev_017",
    content_id: "cnt_011",
    reviewer: "法務 山本",
    role: "legal",
    decision: "approved",
    comment: "キャンペーン条件の表記が適切です。問題ありません。",
    labels: ["legal_ok"],
    created_at: "2026-02-12T10:00:00Z",
  },
  {
    id: "rev_018",
    content_id: "cnt_011",
    reviewer: "ブランド 佐藤",
    role: "brand",
    decision: "approved",
    comment: "新生活応援のメッセージがターゲットに響く内容です。",
    labels: ["brand_ok"],
    created_at: "2026-02-12T11:00:00Z",
  },
  {
    id: "rev_019",
    content_id: "cnt_012",
    reviewer: "法務 山本",
    role: "legal",
    decision: "revision_requested",
    comment: "「初回限定」の条件をより明確に記載してください。",
    labels: ["legal_check"],
    created_at: "2026-02-13T10:00:00Z",
  },
  {
    id: "rev_020",
    content_id: "cnt_012",
    reviewer: "佐藤",
    role: "brand",
    decision: "approved",
    comment: "「お一人様1回限り、過去に購入履歴のない方が対象」と追記しました。",
    labels: [],
    created_at: "2026-02-13T11:00:00Z",
    reply_to: "rev_019",
  },
  {
    id: "rev_021",
    content_id: "cnt_013",
    reviewer: "管理栄養士 田中",
    role: "supervisor",
    decision: "approved",
    comment: "プロアスリートの事例が具体的で説得力があります。監修完了。",
    labels: ["evidence_ok", "supervisor_ok"],
    created_at: "2026-02-14T16:00:00Z",
  },
  {
    id: "rev_022",
    content_id: "cnt_015",
    reviewer: "法務 山本",
    role: "legal",
    decision: "approved",
    comment: "法人向けサービスの説明として適切です。",
    labels: ["legal_ok"],
    created_at: "2026-02-16T11:00:00Z",
  },
  {
    id: "rev_023",
    content_id: "cnt_015",
    reviewer: "ブランド 佐藤",
    role: "brand",
    decision: "approved",
    comment: "B2B向けのトーンとして適切です。",
    labels: ["brand_ok"],
    created_at: "2026-02-16T12:00:00Z",
  },
  {
    id: "rev_024",
    content_id: "cnt_016",
    reviewer: "法務 山本",
    role: "legal",
    decision: "revision_requested",
    comment: "プライバシーポリシーへのリンクを追加してください。",
    labels: ["legal_check"],
    created_at: "2026-02-17T10:00:00Z",
  },
  {
    id: "rev_025",
    content_id: "cnt_016",
    reviewer: "田中",
    role: "supervisor",
    decision: "approved",
    comment: "リンクを追加しました。ご確認ください。",
    labels: [],
    created_at: "2026-02-17T11:00:00Z",
    reply_to: "rev_024",
  },
  {
    id: "rev_026",
    content_id: "cnt_017",
    reviewer: "法務 山本",
    role: "legal",
    decision: "revision_requested",
    comment: "ダイエット関連は景表法の観点から慎重に。「必ず痩せる」等の表現は避けてください。",
    labels: ["legal_check"],
    created_at: "2026-02-18T10:00:00Z",
  },
  {
    id: "rev_027",
    content_id: "cnt_017",
    reviewer: "鈴木",
    role: "brand",
    decision: "approved",
    comment: "「個人差があります」の注釈を追加し、数値目標の記載を削除しました。",
    labels: [],
    created_at: "2026-02-18T11:00:00Z",
    reply_to: "rev_026",
  },
  {
    id: "rev_028",
    content_id: "cnt_018",
    reviewer: "管理栄養士 田中",
    role: "supervisor",
    decision: "approved",
    comment: "ジュニア向けセミナーの内容として適切です。保護者への配慮もOK。",
    labels: ["evidence_ok", "supervisor_ok"],
    created_at: "2026-02-19T16:00:00Z",
  },
  {
    id: "rev_029",
    content_id: "cnt_018",
    reviewer: "ブランド 佐藤",
    role: "brand",
    decision: "approved",
    comment: "ファミリー層へのアプローチとして良いです。",
    labels: ["brand_ok"],
    created_at: "2026-02-19T17:00:00Z",
  },
  {
    id: "rev_030",
    content_id: "cnt_019",
    reviewer: "管理栄養士 田中",
    role: "supervisor",
    decision: "revision_requested",
    comment: "子どもの必要カロリーの記載に誤りがあります。修正をお願いします。",
    labels: ["evidence_check"],
    created_at: "2026-02-20T10:00:00Z",
  },
  {
    id: "rev_031",
    content_id: "cnt_019",
    reviewer: "田中",
    role: "supervisor",
    decision: "approved",
    comment: "最新のガイドラインに基づいて数値を修正しました。",
    labels: [],
    created_at: "2026-02-20T14:00:00Z",
    reply_to: "rev_030",
  },
  {
    id: "rev_032",
    content_id: "cnt_021",
    reviewer: "法務 山本",
    role: "legal",
    decision: "approved",
    comment: "シニア向けコンテンツとして適切な表現です。「かかりつけ医にご相談」の注釈もOK。",
    labels: ["legal_ok"],
    created_at: "2026-02-22T10:00:00Z",
  },
  {
    id: "rev_033",
    content_id: "cnt_021",
    reviewer: "管理栄養士 田中",
    role: "supervisor",
    decision: "approved",
    comment: "シニア向けの栄養アドバイスとして適切です。監修完了。",
    labels: ["evidence_ok", "supervisor_ok"],
    created_at: "2026-02-22T11:00:00Z",
  },
  {
    id: "rev_034",
    content_id: "cnt_022",
    reviewer: "ブランド 佐藤",
    role: "brand",
    decision: "revision_requested",
    comment: "シニア向けのトーンをもう少し柔らかくしてほしいです。",
    labels: ["brand_check"],
    created_at: "2026-02-23T10:00:00Z",
  },
  {
    id: "rev_035",
    content_id: "cnt_022",
    reviewer: "田中",
    role: "supervisor",
    decision: "approved",
    comment: "文体を見直し、より親しみやすい表現に修正しました。",
    labels: [],
    created_at: "2026-02-23T14:00:00Z",
    reply_to: "rev_034",
  },
  {
    id: "rev_036",
    content_id: "cnt_023",
    reviewer: "法務 山本",
    role: "legal",
    decision: "approved",
    comment: "新商品発売キャンペーンの条件表記が適切です。",
    labels: ["legal_ok"],
    created_at: "2026-02-24T10:00:00Z",
  },
  {
    id: "rev_037",
    content_id: "cnt_023",
    reviewer: "ブランド 佐藤",
    role: "brand",
    decision: "revision_requested",
    comment: "パッケージ画像をより目立つ位置に配置してください。",
    labels: ["brand_check"],
    created_at: "2026-02-24T11:00:00Z",
  },
  {
    id: "rev_038",
    content_id: "cnt_023",
    reviewer: "鈴木",
    role: "brand",
    decision: "approved",
    comment: "画像配置を修正しました。ファーストビューでパッケージが見えるようにしています。",
    labels: [],
    created_at: "2026-02-24T14:00:00Z",
    reply_to: "rev_037",
  },
];

export const samplePublishJobs: PublishJob[] = [
  {
    id: "pj_001",
    content_id: "cnt_001",
    channel: "instagram_reels",
    status: "queued",
    scheduled_at: "2026-03-05T12:00:00Z",
  },
  {
    id: "pj_002",
    content_id: "cnt_003",
    channel: "line",
    status: "published",
    scheduled_at: "2026-02-15T09:00:00Z",
    published_at: "2026-02-15T09:01:00Z",
  },
  {
    id: "pj_003",
    content_id: "cnt_011",
    channel: "instagram_reels",
    status: "queued",
    scheduled_at: "2026-03-15T12:00:00Z",
  },
];

export const sampleMetrics: MetricDaily[] = [
  {
    id: "m_001",
    content_id: "cnt_001",
    channel: "instagram_reels",
    date: "2026-03-05",
    impressions: 12500,
    engagements: 890,
    clicks: 210,
    conversions: 18,
    custom: { saves: 145, shares: 67, completion_rate: 0.42 },
  },
  {
    id: "m_002",
    content_id: "cnt_003",
    channel: "line",
    date: "2026-02-15",
    impressions: 8500,
    engagements: 620,
    clicks: 180,
    conversions: 25,
    custom: { open_rate: 0.65, click_rate: 0.12 },
  },
  {
    id: "m_003",
    content_id: "cnt_004",
    channel: "note",
    date: "2026-02-20",
    impressions: 3200,
    engagements: 450,
    clicks: 95,
    conversions: 8,
    custom: { likes: 120, comments: 15 },
  },
];
